/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pai.tech;
import java.sql.*;
import conectabd.conectabanco;
import java.awt.event.KeyEvent;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BESKOW-NOTE
 */
public class Login extends javax.swing.JFrame {

   Connection conecta = null;
   PreparedStatement prepara = null;
   ResultSet resulta = null;
    
    
    public Login() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        conecta = conectabanco.conectabanco();
    }

    public void logar()
    {
        
        String sql = "Select * from login where usuario = ? and senha = ? ";
        try
        {
            prepara = conecta.prepareStatement(sql);
            prepara.setString(1, login_campousuario.getText());
            prepara.setString(2, login_camposenha.getText());
            
            resulta=prepara.executeQuery();
            
            if (resulta.next())
            {
                tela_principal login_tela = new tela_principal();
                login_tela.setVisible(true);
                dispose();
                
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Usuario ou senha inválidos");
                
            }
        }
        
        catch(SQLException error)
                {
                JOptionPane.showMessageDialog(null, error);
           
                    
                }
        
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_botaologin = new javax.swing.JToggleButton();
        login_botaosair = new javax.swing.JToggleButton();
        login_camposenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        login_campousuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("login"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario");
        jLabel2.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Senha");

        login_botaologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/accept.png"))); // NOI18N
        login_botaologin.setText("Login");
        login_botaologin.setName(""); // NOI18N
        login_botaologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_botaologinActionPerformed(evt);
            }
        });
        login_botaologin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_botaologinKeyPressed(evt);
            }
        });

        login_botaosair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cross.png"))); // NOI18N
        login_botaosair.setText("Sair");
        login_botaosair.setActionCommand("");
        login_botaosair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_botaosairActionPerformed(evt);
            }
        });
        login_botaosair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_botaosairKeyPressed(evt);
            }
        });

        login_camposenha.setAlignmentX(0.0F);
        login_camposenha.setAlignmentY(0.0F);
        login_camposenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_camposenhaKeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/paitech.jpg"))); // NOI18N

        login_campousuario.setAlignmentX(0.0F);
        login_campousuario.setAlignmentY(0.0F);
        login_campousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_campousuarioActionPerformed(evt);
            }
        });
        login_campousuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_campousuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login_botaologin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(login_botaosair, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(login_camposenha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_campousuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_campousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(login_camposenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_botaologin)
                    .addComponent(login_botaosair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_camposenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_camposenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_login_camposenhaKeyPressed

    private void login_botaosairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_botaosairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_login_botaosairActionPerformed

    private void login_botaologinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_botaologinKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_login_botaologinKeyPressed

    private void login_botaologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_botaologinActionPerformed
        // TODO add your handling code here:

        logar();
    }//GEN-LAST:event_login_botaologinActionPerformed

    private void login_campousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_campousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_campousuarioActionPerformed

    private void login_campousuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_campousuarioKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_login_campousuarioKeyPressed

    private void login_botaosairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_botaosairKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.exit(0);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_login_botaosairKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton login_botaologin;
    private javax.swing.JToggleButton login_botaosair;
    private javax.swing.JPasswordField login_camposenha;
    private javax.swing.JTextField login_campousuario;
    // End of variables declaration//GEN-END:variables
}
